# Generated by Django 4.2.8 on 2023-12-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
