# Generated by Django 4.2.8 on 2023-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('total_harga', models.FloatField()),
                ('promo_used', models.BooleanField(default=False)),
                ('status_order', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('pelanggan_name', models.CharField(max_length=100)),
            ],
        ),
    ]
