# Generated by Django 4.2.8 on 2023-12-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.FloatField()),
                ('promo_used', models.BooleanField(default=False)),
                ('status_order', models.CharField(max_length=50)),
                ('items', models.ManyToManyField(to='orderhistory.item')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderhistory.pelanggan')),
            ],
        ),
    ]
