# Generated by Django 4.1 on 2023-11-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('ID_promo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama_promo', models.CharField(default='', max_length=200)),
                ('deskripsi_promo', models.TextField()),
                ('masa_berlaku', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('ID_menu', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('harga', models.FloatField(default=0)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.promo')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.menu')),
            ],
        ),
    ]
