# Generated by Django 4.1 on 2023-11-30 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='promo',
        ),
        migrations.AddField(
            model_name='item',
            name='harga',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='nama_item',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
