# Generated by Django 4.1 on 2023-12-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_item_id_remove_item_menu_remove_menu_promo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
