# Generated by Django 4.1 on 2023-12-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_item_user_alter_item_nama_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ID_item',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
