# Generated by Django 4.1 on 2023-12-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_item_id_item_alter_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kuantitas',
            field=models.IntegerField(default=1),
        ),
    ]
