# Generated by Django 4.1 on 2023-12-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_item_kuantitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ID_item',
            field=models.CharField(default=0, max_length=200, primary_key=True, serialize=False),
        ),
    ]
