# Generated by Django 4.2.8 on 2023-12-11 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='diskon_promo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
