# Generated by Django 4.1 on 2023-11-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_userdatamodel_name_userdatamodel_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
